version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "SAM-API"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1rmxgdpw0qkcl"
s3_prefix = "SAM-API"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
